# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [3]:
import numpy as np
import itertools


def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix


def factorial(n):
    '''
    Func return factorial of 'n'
    '''
    j = 1
    for i in range(1, n+1):
        j = j*i
    return j


def permutations_list(matrix):
    '''
    The fucntion return permutations(list_permutations) list for matrix and it`s sign(as 1 or -1)
    '''
    n = len(matrix)
    permutations_index = list(itertools.permutations(list(i for i in range(1, n+1)), n))
    list_ALL_permutations = []
    for item in permutations_index:
        k = 1
        for i in range(len(item)):
            list_ALL_permutations.append(int(matrix[i][int(item[i])-1]))    
            for Item in range(i):
                if item[Item] > item[i]:
                    k *= -1
        list_ALL_permutations.append(k)
    list_permutations = np.array_split(list_ALL_permutations, factorial(n))
    return list_permutations


def calc_multiplication(list_permutations):
    '''
    The function finds the sign and product of permutations
    '''
    list_multiplication = []
    for item in list_permutations:
        list_multiplication.append(np.prod(item))
    return list_multiplication


def calc_sum(list_multiplication):
    '''
    The fucntion calculate det(A)
    find sum of multiplication of permutation
    '''
    d = sum(list_multiplication)
    return d


def is_input_true(n):
    try:
        n = int(n)
        if n >= 0:
            return True
        else:
            print('size cann`t be negative')
            return False
    except ValueError:
        print('size cann`t be this')
        return False


n = input('size matrix(n*n): ')
while not is_input_true(n):
    n = input('size matrix(n*n): ')
n = int(n)


matrix = random_matrix(n)
print(matrix)
print('-'*10)
print('det(A) is: ' + str(calc_sum(calc_multiplication(permutations_list(matrix)))))
print('det(A) as np.linalg.det(a): ' + str(round(np.linalg.det(matrix),3))) 


size cann`t be negative
size cann`t be this
[[3 4 1]
 [5 7 7]
 [6 7 5]]
----------
det(A) is: 19
det(A) as np.linalg.det(a): 19.0
